# Admin credentials for Grafana
adminUser: "admin"
adminPassword: "admin"

# Dashboard provisioning configuration
apiVersion: 1
providers:
  - name: 'default'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    editable: true
    options:
      path: /var/lib/grafana/dashboards

# Additional Grafana settings (optional)
grafana:
  enabled: true
  image: grafana/grafana:latest
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 10Gi
