# Admin credentials for Grafana
adminUser: "admin"
adminPassword: "admin"

# Dashboard provisioning configuration
apiVersion: 1
providers:
  - name: 'default'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    editable: true
    options:
      path: dashboard.json

