apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-shop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hfxbse/dhbw-devops.git
    path: infrastructure/kubernetes
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    managedNamespaceMetadata:
      labels:
        any: label
        you: like
      annotations:
        annotations: on-the-namespace
        applies: for
        the: same
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - kind: ConfigMap
      jqPathExpressions:
        - .data["config.yaml"].auth
    - group: '*'
      kind: '*'
      name: my-deployment
      namespace: my-namespace
      managedFieldsManagers:
        - kube-controller-manager
  revisionHistoryLimit: 10
