apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
  namespace: devops-shop
  labels:
    app: shop-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-backend
  template:
    metadata:
      labels:
        app: shop-backend
    spec:
      containers:
      - name: shop-backend
        image: ghcr.io/hfxbse/dhbw-devops/server:latest
        ports:
        - containerPort: 8080
