apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  namespace: devops-shop
  labels:
    app: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: ghcr.io/hfxbse/dhbw-devops/products:latest
        ports:
        - containerPort: 8081
