apiVersion: v1
kind: Service
metadata:
  name: shop-backend
  namespace: devops-shop
spec:
  selector:
    app.kubernetes.io/name: shop-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
