name: "deb-packager-generation"
run-name: ".deb packager generation"
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore
      - infrastructure/playbook.yml
      - infrastructure/Vagrantfile

jobs:
  generate-deb-packager:
    runs-on: ubuntu-24.04

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: "Checkout repository"

      - uses: VaultVulp/gp-docker-action@1.6.0
        name: "Build and upload Docker image"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: server
          build-context: .
          dockerfile: infrastructure/Dockerfile
