on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[A-Za-z0-9]+-service-[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
          release-type: simple
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          